version: '2'

volumes:
  node_modules: {}

services:
  node:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    command: /www/start-dev.sh
    ports:
      - "9000:9000"
    volumes:
      - ./app:/www/app
      - node_modules:/www/app/node_modules

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    # command: ["python", "-m", "http.server"]
    command: ["./manage.py", "runserver", "0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
